image: node:latest

stages:
  - build
  - deploy

cache:
  untracked: true
  paths:
    - node_modules/

before_script:
  - node --version
  - npm --version

bundle:
  stage: test
  script:
    - npm install --loglevel http
    - npm run build
  tags:
    - node