variables:
  DEPLOY_USER: "gitlab"
  DEPLOY_SERVER: "dev-serever.mdi.ru"
  DEPLOY_PATH: "/opt/ursip/summoners"

before_script:
  - node --version
  - npm --version
  - npm install --loglevel http

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script: 
    - npm run build
  artifacts:
    paths:
    - build

developDeploy:
  stage: deploy
  only: 
    - develop
  script: 
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "rm -fR $DEPLOY_PATH/*"
    - scp -r build/* $DEPLOY_USER@$DEPLOY_SERVER:DEPLOY_PATH

masterDeploy:
  stage: deploy
  only: 
    - master
  script: 
    - echo "masterDeploy"